use master
drop database despensa;

CREATE DATABASE DESPENSA;
USE DESPENSA;

CREATE TABLE USUARIO(
ID_USUARIO INT IDENTITY(1,1) NOT NULL,
NOME VARCHAR (40) NOT NULL,
EMAIL VARCHAR (50) NOT NULL ,
SENHA VARCHAR (100) NOT NULL,
CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO)
)



CREATE TABLE CATEGORIA(
ID_CATEGORIA INT IDENTITY(1,1) NOT NULL,
DESCRI_CATEG VARCHAR (20) NOT NULL,
CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID_CATEGORIA)
)

CREATE TABLE LOCAL_ARMAZ(
ID_LOCAL INT IDENTITY(1,1) NOT NULL,
DESCRI_LOCAL VARCHAR (20) NOT NULL
CONSTRAINT PK_LOCAL_ARMAZ PRIMARY KEY (ID_LOCAL)
)



CREATE TABLE PRODUTOS(
COD_PROD INT IDENTITY(1,1) NOT NULL,
NOME_PROD VARCHAR(50) NULL,
VALIDADE DATETIME NULL,
EAN VARCHAR(100) NULL,
QUANT VARCHAR (10) NULL,
ID_CATEGORIA INT NOT NULL,
ID_LOCAL INT NOT NULL,
ID_USUARIO INT NOT NULL,
CONSTRAINT PK_PROD PRIMARY KEY (COD_PROD),
CONSTRAINT FK_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA),
CONSTRAINT FK_LOCAL_ARMZ FOREIGN KEY (ID_LOCAL) REFERENCES LOCAL_ARMAZ(ID_LOCAL),
CONSTRAINT FK_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
)

insert into CATEGORIA values (1, 'Bebidas')
insert into CATEGORIA values (2, 'Frutas')
insert into CATEGORIA values (3, 'Não Perecíveis')
insert into CATEGORIA values (4, 'Temperos')
insert into CATEGORIA values (5, 'Outros')

insert into LOCAL_ARMAZ values (1, 'Geladeira')
insert into LOCAL_ARMAZ values (2, 'Armário')

SELECT * FROM USUARIO
SELECT * FROM PRODUTOS
SELECT * FROM CATEGORIA
SELECT * FROM LOCAL_ARMAZ


insert into USUARIO values ('Carlos','carlos@gmail.com','1234')